# Generated by Django 3.2.5 on 2021-08-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0003_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
